// Seed the database with initial data from the static signals.ts file
// This runs once on startup if the DB is empty

import { storage } from "./storage";

export function seedDatabaseIfEmpty() {
  const count = storage.getSignalCount();
  if (count > 0) return; // Already seeded

  console.log("[SEED] Seeding database with initial intelligence data...");

  // ==================== SIGNALS ====================
  const signalsData = [
    { signalId: "SIG-001", title: "PPWR enters force 12 August 2026", summary: "The EU Packaging and Packaging Waste Regulation applies across all 27 Member States from August 12, imposing chemical restrictions, EPR registration, and traceability obligations.", whyItMatters: "This is a market-access prerequisite. All packaging placed on EU market must comply — no grace period after August 12.", clientImplication: "Brands need Declarations of Conformity for every packaging type. Labels must carry batch/serial numbers and manufacturer identification.", suggestedAction: "Complete full packaging audit; collect DoCs from suppliers; map EPR producer obligations by Member State.", type: "regulation", impactLevel: "critical", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "action-required", date: "2026-03-20", source: "European Commission / EUR-Lex" },
    { signalId: "SIG-002", title: "ESPR unsold goods destruction ban — July 19, 2026", summary: "Large and medium enterprises cannot destroy unsold textiles and footwear from July 19, 2026. Direct ESPR provision, no further legislation needed.", whyItMatters: "Creates structural demand for recommerce, donation, and recycling infrastructure. Inventory management becomes critical.", clientImplication: "Brands need RFID-enabled inventory tracking to prove compliance. Hangers with embedded digital identity become essential.", suggestedAction: "Position RFID/traceability solutions for inventory management compliance with large retail customers.", type: "regulation", impactLevel: "critical", suites: '["Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "action-required", date: "2026-03-18", source: "European Commission / EUR-Lex" },
    { signalId: "SIG-003", title: "Greenwashing rules active September 27, 2026", summary: "ECGT bans generic environmental claims (eco-friendly, green, sustainable) without certification. Carbon offset-based claims prohibited.", whyItMatters: "Every sustainability claim on packaging, labels, and hangtags must be verifiable. Generic green claims become illegal.", clientImplication: "All packaging copy, label text, and marketing claims must be audited. Mainetti branding solutions must support compliant messaging.", suggestedAction: "Audit all sustainability messaging across product lines. Offer clients a label/tag compliance review service.", type: "regulation", impactLevel: "critical", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "action-required", date: "2026-03-15", source: "European Commission" },
    { signalId: "SIG-004", title: "Digital Product Passport — textile delegated act 2027", summary: "EU DPP for textiles confirmed for 2027 delegated act adoption with mandatory compliance 2028-2029. Every garment will need a digital identity.", whyItMatters: "DPP will require QR-code-enabled labels and tags on every garment. This is a massive opportunity for Mainetti's branding solutions.", clientImplication: "Brands must plan for DPP integration into labels, hangtags, and packaging. Technology infrastructure decisions needed now.", suggestedAction: "Develop DPP-ready label and tag solutions. Partner with DPP platform providers. Build client advisory capability.", type: "regulation", impactLevel: "critical", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "confirmed", status: "action-required", date: "2026-03-12", source: "European Commission / ESPR" },
    { signalId: "SIG-005", title: "LVMH zero virgin fossil-based plastic by 2026", summary: "LVMH committed to eliminating virgin fossil-based plastic from customer packaging this year. Every dust bag, shopping bag, and box affected.", whyItMatters: "LVMH is Mainetti's largest potential client for premium packaging. Their zero-plastic commitment drives immediate material sourcing changes.", clientImplication: "All packaging suppliers must offer certified non-virgin-plastic alternatives. Premium paper, recycled, and bio-based materials required.", suggestedAction: "Ensure product branding materials meet LVMH zero-virgin-plastic standard. Prepare material certification documentation.", type: "client-signal", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "Global", confidence: "confirmed", status: "action-required", date: "2026-03-08", source: "LVMH Life 360 Report" },
    { signalId: "SIG-006", title: "SML Group receives $600M+ PE investment", summary: "FountainVest and CPE invested over $600M in SML Group (Nov 2025), Mainetti's most direct competitor in brand identification solutions.", whyItMatters: "SML is now substantially better capitalised. Expect accelerated R&D, acquisitions, and market expansion in RFID and digital identity.", clientImplication: "Clients may see more aggressive SML pricing and capability pitches. Mainetti must differentiate on integration and service breadth.", suggestedAction: "Brief commercial teams on SML investment implications. Review competitive positioning. Identify differentiation opportunities.", type: "competitor", impactLevel: "high", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-03-10", source: "SML Group / FountainVest" },
    { signalId: "SIG-007", title: "Checkpoint Systems launches integrated RFID checkout solution", summary: "Checkpoint launched an integrated RFID checkout solution (Feb 2026), combining loss prevention with frictionless checkout at retail point of sale.", whyItMatters: "RFID-enabled retail checkout is becoming mainstream. Hangers and tags with embedded RFID are a prerequisite.", clientImplication: "Retailers adopting RFID checkout will need RFID-enabled hangers and tags from production onwards.", suggestedAction: "Position Mainetti's intelligent solutions (RFID hangers/tags) for the RFID checkout use case.", type: "competitor", impactLevel: "high", suites: '["Retail Experience","Product Branding"]', timeHorizon: "immediate", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-03-05", source: "Checkpoint Systems" },
    { signalId: "SIG-008", title: "CBAM definitive regime live — affects packaging inputs", summary: "EU Carbon Border Adjustment Mechanism definitive phase began Jan 1, 2026. Steel, aluminium, cement, fertilizers now subject to carbon import duties.", whyItMatters: "CBAM affects material costs for packaging containing aluminium and steel. Transit packaging and structural packaging costs may rise.", clientImplication: "Clients sourcing packaging with metal components face higher costs. Switch to non-CBAM materials or EU-sourced inputs becomes attractive.", suggestedAction: "Map Mainetti supply chain for CBAM-exposed materials. Offer clients material substitution advisory.", type: "regulation", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-03-01", source: "European Commission / DG TAXUD" },
    { signalId: "SIG-009", title: "Inditex Green to Pack — circular hanger program accelerating", summary: "Inditex expanding its Green to Pack program for circular packaging and hangers. Closed-loop hanger reuse and recycled materials are now procurement criteria.", whyItMatters: "Inditex is the world's largest fashion retailer. Their circular hanger requirements set industry standards.", clientImplication: "All hanger suppliers must prove circular credentials. Hangerloop-type programs become competitive necessities.", suggestedAction: "Strengthen Hangerloop program positioning for Inditex. Ensure circularity metrics and certifications are client-ready.", type: "client-signal", impactLevel: "high", suites: '["Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-03-06", source: "Inditex Annual Report" },
    { signalId: "SIG-010", title: "CSRD Omnibus I — scope narrowed to >1000 employees", summary: "Directive (EU) 2026/470 published Feb 26, 2026. CSRD reporting threshold raised to >1,000 employees AND >€450M turnover.", whyItMatters: "Fewer mid-size companies now subject to mandatory sustainability reporting. But large clients remain covered and will demand supply chain data.", clientImplication: "Large brand clients will still need supply chain sustainability data from Mainetti. Smaller clients get temporary relief.", suggestedAction: "Maintain sustainability data readiness for Tier 1 clients. Communicate simplified requirements to mid-market accounts.", type: "regulation", impactLevel: "medium", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-02-26", source: "EUR-Lex / Official Journal" },
    { signalId: "SIG-011", title: "Avery Dennison launches Optica RFID portfolio", summary: "Avery Dennison launched its flagship Optica RFID suite at NRF 2025, offering end-to-end supply chain visibility and digital product identity.", whyItMatters: "Avery Dennison is the market leader in RFID/digital identity. The Optica suite sets the competitive benchmark for traceability solutions.", clientImplication: "Clients comparing RFID solutions will benchmark against Avery Dennison Optica. Mainetti must articulate differentiated value.", suggestedAction: "Develop competitive positioning against Optica. Emphasize Mainetti's integrated approach across branding + retail + supply chain.", type: "competitor", impactLevel: "high", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-01-15", source: "Avery Dennison / NRF 2025" },
    { signalId: "SIG-012", title: "CEN/CENELEC DPP standards deadline March 31, 2026", summary: "CEN JTC 24 standards for Digital Product Passport (prEN 1821x series) have a publication deadline of March 31, 2026.", whyItMatters: "These standards will define the technical requirements for DPP implementation across textiles. They shape what QR codes and data carriers must contain.", clientImplication: "Brands and their packaging/label suppliers must align to the published standards. Label and tag specifications will need updating.", suggestedAction: "Monitor CEN publication. Begin updating label/tag specifications once standards are published.", type: "regulation", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "action-required", date: "2026-03-10", source: "CEN/CENELEC" },
    { signalId: "SIG-013", title: "ECHA finalizing PFAS restriction — packaging implications", summary: "ECHA RAC/SEAC opinion on universal PFAS restriction nearing completion. Packaging with PFAS coatings (water/grease resistance) affected.", whyItMatters: "PFAS restriction would ban forever chemicals in packaging coatings. Affects flexible packaging, some labels, and protective treatments.", clientImplication: "Brands using PFAS-treated packaging materials must plan for reformulation. Timeline 2027-2028 for packaging sector.", suggestedAction: "Audit Mainetti product lines for PFAS content. Develop PFAS-free alternatives for flexible packaging and coatings.", type: "regulation", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "high", status: "monitoring", date: "2026-03-15", source: "ECHA / Plastics Engineering" },
    { signalId: "SIG-014", title: "Sealed Air acquisition by CD&R — $10.3B deal", summary: "CD&R acquiring Sealed Air for $10.3B, expected to close mid-2026. Major consolidation in protective/transit packaging.", whyItMatters: "Consolidation changes the competitive landscape in protective and transit packaging. Post-acquisition strategy may shift market dynamics.", clientImplication: "Clients using Sealed Air for protective packaging may see service disruption or pricing changes during integration.", suggestedAction: "Monitor deal closure. Prepare to capture accounts if Sealed Air integration causes client friction.", type: "competitor", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-02-20", source: "CD&R / Sealed Air" },
    { signalId: "SIG-015", title: "H&M Group targets 100% recycled or sustainably sourced packaging by 2030", summary: "H&M Group has reinforced its commitment to ensure all packaging is recycled or sustainably sourced by 2030, with interim 2025 targets.", whyItMatters: "H&M is a major potential client. Their packaging sustainability targets create procurement criteria that suppliers must meet.", clientImplication: "Packaging suppliers to H&M must demonstrate recycled content and sustainable sourcing certifications.", suggestedAction: "Ensure Mainetti packaging solutions meet H&M 2025/2030 sustainability procurement criteria.", type: "client-signal", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-02-15", source: "H&M Group Sustainability Report" },
    { signalId: "SIG-016", title: "Kering commits to eliminate plastic packaging by 2025", summary: "Kering (Gucci, Saint Laurent, Bottega Veneta) has committed to eliminate non-essential plastic from packaging and increase use of recycled materials.", whyItMatters: "Kering's luxury brands require premium sustainable packaging — dust bags, boxes, labels, tags. Directly in Mainetti's sweet spot.", clientImplication: "Luxury packaging must be plastic-free and premium-looking. Material innovation and premium paper/fabric solutions in high demand.", suggestedAction: "Develop and present Kering-ready plastic-free branding solutions. Leverage bespoke boxes, fabric dust bags, paper-based alternatives.", type: "client-signal", impactLevel: "high", suites: '["Product Branding"]', timeHorizon: "immediate", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-01-20", source: "Kering Sustainability Progress Report" },
    { signalId: "SIG-017", title: "Marks & Spencer achieves 100% recyclable own-brand packaging", summary: "M&S has achieved its target of making all own-brand packaging recyclable, compostable, or reusable by end of 2025.", whyItMatters: "Demonstrates that 100% recyclable packaging is achievable at scale. Sets benchmark that other retailers will follow.", clientImplication: "Retailers lagging M&S will accelerate recyclable packaging procurement. Suppliers must offer recyclable-by-design solutions.", suggestedAction: "Use M&S as case study for clients. Position Mainetti's recyclable packaging portfolio.", type: "client-signal", impactLevel: "medium", suites: '["Supply Chain / Product Movement","Product Branding"]', timeHorizon: "short-term", geography: "UK", confidence: "confirmed", status: "monitoring", date: "2026-01-10", source: "M&S Plan A Report" },
    { signalId: "SIG-018", title: "Paper-based hanger innovation accelerating", summary: "Multiple competitors launching paper/FSC-certified hangers: Braiform (300M/yr reuse), Nexgen/Kiabi (FSC paper), (re)x (ocean plastic premium). Mainetti's Paperform launched Dec 2025.", whyItMatters: "Paper/sustainable hangers becoming a competitive battleground. First-mover advantage is narrowing.", clientImplication: "Retailers and brands actively seeking paper hanger alternatives. Decision cycles are shortening.", suggestedAction: "Accelerate Paperform rollout. Develop clear competitive differentiation vs. Braiform, Nexgen, (re)x alternatives.", type: "market-trend", impactLevel: "high", suites: '["Retail Experience"]', timeHorizon: "immediate", geography: "Global", confidence: "confirmed", status: "action-required", date: "2026-03-01", source: "Industry analysis" },
    { signalId: "SIG-019", title: "Zalando requires DPP for brand listings", summary: "Zalando now requires valid Digital Product Passport data before listing brands on its platform. Voluntary now, mandatory by 2027.", whyItMatters: "Major e-commerce platforms becoming DPP gatekeepers. Brands without DPP-ready labels lose market access.", clientImplication: "Brands selling through Zalando must have DPP-enabled product labeling. QR codes on labels/tags become a listing prerequisite.", suggestedAction: "Offer DPP label solutions to brands selling through Zalando. Fast-track QR-code-enabled label portfolio.", type: "client-signal", impactLevel: "high", suites: '["Product Branding"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "high", status: "action-required", date: "2026-02-28", source: "Zalando Partner Program" },
    { signalId: "SIG-020", title: "French EPR levies expand to professional packaging — July 2026", summary: "Citeo Pro launches professional packaging EPR levies from July 1, 2026 under AGEC law. All B2B packaging placed on French market must register.", whyItMatters: "France leading on EPR expansion. B2B packaging (transit, industrial) now under EPR — affects Mainetti's supply chain suite.", clientImplication: "Clients with French operations need B2B packaging EPR registration. Compliance documentation and eco-contribution payments required.", suggestedAction: "Alert French country leads. Prepare client advisory on Citeo Pro registration requirements.", type: "regulation", impactLevel: "high", suites: '["Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "France", confidence: "confirmed", status: "action-required", date: "2026-03-05", source: "Citeo Pro / AGEC" },
    { signalId: "SIG-021", title: "Smurfit Westrock uses AI for luxury packaging design", summary: "Smurfit Westrock ($31.2B revenues) deploying AI to design luxury packaging, directly targeting the same premium brand clients as Mainetti.", whyItMatters: "A well-resourced competitor entering luxury packaging with AI-driven design capability. Threatens Mainetti's premium positioning.", clientImplication: "Luxury clients may consider AI-optimized packaging design alternatives. Mainetti must emphasize craftsmanship + sustainability + integration.", suggestedAction: "Monitor Smurfit Westrock luxury packaging initiatives. Strengthen Mainetti's luxury design advisory positioning.", type: "competitor", impactLevel: "medium", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "Global", confidence: "high", status: "monitoring", date: "2026-02-10", source: "Smurfit Westrock" },
    { signalId: "SIG-022", title: "Germany VerpackDG enters force August 12, 2026", summary: "Germany's national implementation of PPWR (VerpackDG) aligned with EU application date. LUCID registry updates required for all packaging producers.", whyItMatters: "Germany is the largest EU packaging market. Compliance with LUCID/ZSVR is mandatory for market access.", clientImplication: "All clients placing packaged goods on German market must update LUCID registrations. Non-compliance risks fines and market exclusion.", suggestedAction: "Brief German country leads. Prepare client support for LUCID/ZSVR registration updates.", type: "regulation", impactLevel: "high", suites: '["Supply Chain / Product Movement","Product Branding"]', timeHorizon: "immediate", geography: "Germany", confidence: "confirmed", status: "action-required", date: "2026-03-08", source: "ZSVR / German Federal Government" },
    { signalId: "SIG-023", title: "UK modulated EPR fees enforceable October 2026", summary: "UK PackUK scheme with modulated EPR fees based on recyclability enters full enforcement from October 2026.", whyItMatters: "UK EPR creates financial incentive for recyclable packaging. Higher fees for hard-to-recycle materials.", clientImplication: "UK clients face higher EPR costs for non-recyclable packaging. Switching to recyclable alternatives saves money.", suggestedAction: "Position recyclable packaging solutions for UK market. Quantify EPR cost savings for client business cases.", type: "regulation", impactLevel: "medium", suites: '["Supply Chain / Product Movement","Product Branding"]', timeHorizon: "short-term", geography: "UK", confidence: "confirmed", status: "monitoring", date: "2026-02-25", source: "DEFRA / PackUK" },
    { signalId: "SIG-024", title: "PPWR harmonized QR labeling mandatory from 2028", summary: "PPWR requires harmonized QR code labels on all packaging from 2028 — containing material composition, recyclability, and EPR data.", whyItMatters: "QR codes on packaging become legally required. This is a massive labeling infrastructure change across all packaging types.", clientImplication: "Every label, hangtag, and packaging item must integrate QR codes by 2028. Design templates, print specifications, and data systems need preparation.", suggestedAction: "Develop modular QR label infrastructure now. Offer early-adoption QR labeling pilots to key clients.", type: "regulation", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-03-12", source: "PPWR / EUR-Lex" },
    { signalId: "SIG-025", title: "Recycled content minimums — 35% plastic packaging by 2030", summary: "PPWR mandates 35% recycled content in plastic packaging by 2030, rising to 65% by 2040. Contact-sensitive packaging has different timelines.", whyItMatters: "Material procurement must shift to recycled inputs. Affects flexible packaging, protective films, and plastic-based branding materials.", clientImplication: "Clients must plan material sourcing transitions. Packaging cost increases likely during ramp-up of recycled material supply.", suggestedAction: "Map Mainetti flexible packaging and plastic materials against recycled content targets. Develop transition roadmaps for clients.", type: "regulation", impactLevel: "high", suites: '["Supply Chain / Product Movement","Product Branding"]', timeHorizon: "medium-term", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-03-01", source: "PPWR / EUR-Lex" },
    { signalId: "SIG-026", title: "EUDR delayed to Dec 30, 2026 for large operators", summary: "EU Deforestation Regulation (EUDR) application delayed to December 30, 2026 for large operators. Paper and leather packaging in scope.", whyItMatters: "Paper-based packaging and leather trims/patches must comply with deforestation-free sourcing. Due diligence documentation required.", clientImplication: "Brands using paper packaging, leather patches, or wood-derived materials need deforestation-free sourcing verification.", suggestedAction: "Map Mainetti paper and leather supply chains for EUDR compliance. Prepare due diligence statements for clients.", type: "regulation", impactLevel: "medium", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-02-15", source: "European Commission / EUDR" },
    { signalId: "SIG-027", title: "De minimis customs duty from July 2026 — €3 threshold", summary: "EU introducing customs duties on all consignments including those below €150, with a €3 minimum duty from July 1, 2026.", whyItMatters: "Affects cross-border e-commerce packaging. May increase demand for cost-efficient, lightweight packaging solutions.", clientImplication: "E-commerce brands shipping to EU face higher costs on small parcels. Packaging optimization becomes a cost lever.", suggestedAction: "Develop lightweight e-commerce packaging solutions. Position transit packaging optimization for cross-border clients.", type: "regulation", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', timeHorizon: "immediate", geography: "EU-wide", confidence: "confirmed", status: "monitoring", date: "2026-03-01", source: "DG TAXUD / European Commission" },
    { signalId: "SIG-028", title: "Walmart Project Gigaton — packaging reduction targets", summary: "Walmart continues to push suppliers on packaging reduction through Project Gigaton. Packaging optimization and waste reduction are procurement criteria.", whyItMatters: "Walmart's procurement influence extends globally. Their packaging requirements shape supplier standards across retail.", clientImplication: "Walmart suppliers must demonstrate packaging reduction progress. Right-sizing, material optimization, and waste metrics tracked.", suggestedAction: "Ensure Mainetti transit/protective packaging meets Walmart sustainability procurement criteria.", type: "client-signal", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "North America", confidence: "confirmed", status: "monitoring", date: "2026-01-25", source: "Walmart ESG Report" },
    { signalId: "SIG-029", title: "Avery Dennison clean-separation recycling adhesives", summary: "Avery Dennison launched recyclable adhesive labels at Labelexpo 2025 that enable clean separation during recycling — directly competitive with Mainetti labels.", whyItMatters: "Recyclable adhesives address a key barrier to label recyclability. AD is setting the standard for sustainable label technology.", clientImplication: "Brands will increasingly specify recyclable adhesive labels. Mainetti must offer comparable technology.", suggestedAction: "Assess Mainetti label adhesive portfolio against AD clean-separation technology. Develop competitive alternative.", type: "competitor", impactLevel: "medium", suites: '["Product Branding"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-01-10", source: "Avery Dennison / Labelexpo" },
    { signalId: "SIG-030", title: "ESPR Working Table meets in Milan — DPP for fashion", summary: "European Climate Pact ESPR Working Table meeting in Milan (March 2026) focused on DPP operational transition for fashion industry.", whyItMatters: "Multi-stakeholder working group shaping how DPP will work in practice for fashion. Outcomes will influence implementation standards.", clientImplication: "DPP implementation guidance emerging from these working groups will define label/tag specifications.", suggestedAction: "Track working group outputs. Ensure Mainetti product development aligns with emerging DPP operational standards.", type: "regulation", impactLevel: "medium", suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", geography: "EU-wide", confidence: "high", status: "monitoring", date: "2026-03-23", source: "European Climate Pact" },
    { signalId: "SIG-031", title: "SML InfuseRFID wins 2026 SEAL Sustainable Product Award", summary: "SML's InfuseRFID technology — which survives wet apparel processing — won the 2026 SEAL Award, boosting their sustainability credentials.", whyItMatters: "SML gaining sustainability recognition strengthens their competitive positioning against Mainetti in sustainable RFID solutions.", clientImplication: "Clients evaluating RFID options may weight SML's sustainability credentials. Mainetti needs comparable recognition.", suggestedAction: "Pursue sustainability certifications for Mainetti's intelligent solutions. Highlight Full Circle and Hangerloop credentials.", type: "competitor", impactLevel: "medium", suites: '["Retail Experience","Product Branding"]', timeHorizon: "short-term", geography: "Global", confidence: "confirmed", status: "monitoring", date: "2026-03-18", source: "Fibre2Fashion / SEAL Awards" },
    { signalId: "SIG-032", title: "Selfridges requires DPP before brand onboarding", summary: "Selfridges has added Digital Product Passport data as a requirement for new brand onboarding on its platform.", whyItMatters: "Premium retailers becoming DPP gatekeepers ahead of regulation. Market access increasingly tied to digital product identity.", clientImplication: "Brands targeting premium retail must have DPP-ready products. Labels and tags must support digital identity data.", suggestedAction: "Fast-track DPP-integrated label solutions. Target brands applying to list on Selfridges and similar premium platforms.", type: "client-signal", impactLevel: "high", suites: '["Product Branding"]', timeHorizon: "immediate", geography: "UK", confidence: "high", status: "action-required", date: "2026-03-01", source: "Selfridges Buying Team" },
  ];

  for (const s of signalsData) {
    storage.createSignal(s);
  }

  // ==================== REGULATIONS ====================
  const regsData = [
    { regId: "REG-001", name: "Packaging and Packaging Waste Regulation", shortName: "PPWR", status: "In force — application Aug 12, 2026", nextMilestone: "Full application across EU", nextMilestoneDate: "2026-08-12", impactLevel: "critical", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Replaces the 1994 Packaging Directive. Harmonises packaging requirements across the EU including recyclability, recycled content, labeling, EPR, and chemical restrictions.", keyRequirements: '["Declaration of Conformity for all packaging","EPR producer registration by Aug 2026","Harmonized QR labels by 2028","Recyclability Grade C minimum by 2030","35% recycled plastic content by 2030","PFAS ban in food packaging from Aug 2026"]' },
    { regId: "REG-002", name: "Ecodesign for Sustainable Products Regulation", shortName: "ESPR", status: "In force — delegated acts ongoing", nextMilestone: "Unsold goods destruction ban", nextMilestoneDate: "2026-07-19", impactLevel: "critical", suites: '["Retail Experience","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Framework regulation setting sustainability requirements for products. Includes the Digital Product Passport mandate and a ban on destruction of unsold goods.", keyRequirements: '["Unsold goods destruction ban from Jul 19, 2026","Digital Product Passport delegated acts 2025-2030","Product-specific sustainability requirements","Textile DPP delegated act 2027"]' },
    { regId: "REG-003", name: "Empowering Consumers for the Green Transition", shortName: "ECGT", status: "In force — application Sep 27, 2026", nextMilestone: "Application date", nextMilestoneDate: "2026-09-27", impactLevel: "critical", suites: '["Product Branding","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Bans generic environmental claims and misleading green marketing. All sustainability claims must be substantiated and independently verified.", keyRequirements: '["Ban on generic green claims (eco-friendly, sustainable)","Ban on carbon offset-based climate neutrality claims","Sustainability labels must be based on certification schemes","Durability and repairability information requirements"]' },
    { regId: "REG-004", name: "Digital Product Passport (Textiles)", shortName: "DPP-Textile", status: "Delegated act expected 2027", nextMilestone: "CEN standards publication", nextMilestoneDate: "2026-03-31", impactLevel: "critical", suites: '["Product Branding","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Every textile product will need a digital identity accessible via QR code, containing material composition, origin, care, recyclability, and environmental data.", keyRequirements: '["QR code data carrier on product/label","Material composition and origin data","Environmental footprint data","Recyclability and circularity information","Supply chain traceability data"]' },
    { regId: "REG-005", name: "EU Deforestation Regulation", shortName: "EUDR", status: "Delayed — Dec 30, 2026 for large operators", nextMilestone: "Application for large operators", nextMilestoneDate: "2026-12-30", impactLevel: "medium", suites: '["Product Branding","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Prohibits placing deforestation-linked commodities on EU market. Relevant for paper packaging, leather trims, and rubber components.", keyRequirements: '["Due diligence statements for wood/paper/leather","Geolocation data for commodity sourcing","Risk assessment and mitigation documentation","Annual reporting for large operators"]' },
    { regId: "REG-006", name: "Corporate Sustainability Reporting Directive (Omnibus I)", shortName: "CSRD", status: "Amended — scope narrowed Feb 2026", nextMilestone: "First reports under new scope", nextMilestoneDate: "2027-01-01", impactLevel: "medium", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Requires large companies to report on sustainability including supply chain impacts. Scope narrowed to >1,000 employees AND >€450M turnover.", keyRequirements: '["ESRS sustainability reporting standards","Double materiality assessment","Value chain due diligence","Third-party assurance of sustainability data"]' },
    { regId: "REG-007", name: "Carbon Border Adjustment Mechanism", shortName: "CBAM", status: "Definitive phase — Jan 1, 2026", nextMilestone: "First CBAM certificate purchases", nextMilestoneDate: "2026-05-31", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', geography: "EU-wide", description: "Imposes carbon costs on imports of steel, aluminium, cement, fertilizers, electricity, and hydrogen. Affects packaging material costs.", keyRequirements: '["Quarterly CBAM declarations","Carbon content verification","CBAM certificate purchases","Third-party verification of embedded emissions"]' },
    { regId: "REG-008", name: "French Professional EPR (AGEC)", shortName: "FR-EPR-Pro", status: "Launching July 1, 2026", nextMilestone: "Citeo Pro levy launch", nextMilestoneDate: "2026-07-01", impactLevel: "high", suites: '["Supply Chain / Product Movement"]', geography: "France", description: "Extends EPR obligations to professional/B2B packaging in France under the AGEC law. All B2B packaging placed on French market must register with Citeo Pro.", keyRequirements: '["Registration with Citeo Pro","Eco-contribution payments for B2B packaging","Reporting of packaging quantities and materials","Compliance documentation for clients"]' },
    { regId: "REG-009", name: "Germany Packaging Act (VerpackDG)", shortName: "VerpackDG", status: "Aligned with PPWR — Aug 12, 2026", nextMilestone: "Full application", nextMilestoneDate: "2026-08-12", impactLevel: "high", suites: '["Supply Chain / Product Movement","Product Branding"]', geography: "Germany", description: "German national implementation of PPWR. Requires LUCID/ZSVR registration updates for all packaging producers and first-distributors.", keyRequirements: '["LUCID registration update","ZSVR compliance verification","System participation for household packaging","Reporting and documentation requirements"]' },
    { regId: "REG-010", name: "UK Extended Producer Responsibility", shortName: "UK-EPR", status: "Modulated fees from Oct 2026", nextMilestone: "Full modulated fee enforcement", nextMilestoneDate: "2026-10-01", impactLevel: "medium", suites: '["Supply Chain / Product Movement","Product Branding"]', geography: "UK", description: "UK PackUK scheme introduces modulated EPR fees based on packaging recyclability. Higher fees for hard-to-recycle materials.", keyRequirements: '["PackUK registration","Modulated fee payments based on recyclability","Packaging data reporting","Recyclability assessment compliance"]' },
    { regId: "REG-011", name: "EU Textile Strategy", shortName: "EU-Textile", status: "Implementation ongoing", nextMilestone: "Textile EPR EU-wide mandatory", nextMilestoneDate: "2026-10-01", impactLevel: "medium", suites: '["Product Branding","Retail Experience"]', geography: "EU-wide", description: "Comprehensive strategy for sustainable textiles covering design, production, and end-of-life. Includes mandatory textile EPR and microfiber management.", keyRequirements: '["Mandatory textile EPR from Oct 2025","Microfiber release requirements","Mandatory recycled fiber content targets","Digital labeling requirements"]' },
    { regId: "REG-012", name: "PFAS Universal Restriction", shortName: "PFAS", status: "RAC/SEAC opinion pending", nextMilestone: "Committee opinion finalization", nextMilestoneDate: "2026-06-30", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]', geography: "EU-wide", description: "Proposed restriction of all per- and polyfluoroalkyl substances (PFAS). Would affect packaging coatings, water-resistant treatments, and certain label materials.", keyRequirements: '["Elimination of PFAS from packaging coatings","Alternative material sourcing","Reformulation of water/grease-resistant treatments","Transition timeline 18-36 months after adoption"]' },
    { regId: "REG-013", name: "Green Claims Directive", shortName: "GCD", status: "Withdrawn June 2025 — ECGT active", nextMilestone: "ECGT application covers scope", nextMilestoneDate: "2026-09-27", impactLevel: "medium", suites: '["Product Branding"]', geography: "EU-wide", description: "Originally a standalone directive, now largely covered by ECGT. Substantiation requirements for environmental claims on products and packaging.", keyRequirements: '["Life cycle assessment basis for claims","Third-party verification","Comparative claims must use common methodology","Environmental labeling scheme requirements"]' },
    { regId: "REG-014", name: "CSDDD (Corporate Due Diligence)", shortName: "CSDDD", status: "Application delayed to July 2029", nextMilestone: "Transposition by Member States", nextMilestoneDate: "2027-07-26", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', geography: "EU-wide", description: "Requires large companies to identify, prevent, and mitigate adverse human rights and environmental impacts in their value chains. Limited to Tier 1 supply chain.", keyRequirements: '["Tier 1 supply chain due diligence","Human rights impact assessment","Environmental impact mitigation","Stakeholder engagement and grievance mechanisms"]' },
    { regId: "REG-015", name: "EU Customs Reform — ICS2 / de minimis duty", shortName: "EU-Customs", status: "In force — de minimis from Jul 2026", nextMilestone: "€3 minimum duty on all consignments", nextMilestoneDate: "2026-07-01", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]', geography: "EU-wide", description: "Reform of EU customs procedures including full implementation of ICS2 pre-arrival screening and introduction of duties on sub-€150 consignments.", keyRequirements: '["ICS2 pre-arrival data submission","De minimis duty on all imports from Jul 2026","Enhanced product safety screening","Digital customs documentation"]' },
  ];

  for (const r of regsData) {
    storage.createRegulation(r);
  }

  // ==================== STAKEHOLDERS ====================
  const stakeholdersData = [
    { stkId: "STK-001", name: "Jessika Roswall", organization: "European Commission", category: "EU Commissioner", geography: "EU-wide", importance: "high", role: "Commissioner for Environment, Water Resilience and Competitive Circular Economy", relevance: "Directly responsible for PPWR, ESPR, and circular economy legislation. Controls packaging and sustainability regulation." },
    { stkId: "STK-002", name: "Stéphane Séjourné", organization: "European Commission", category: "EU Commissioner", geography: "EU-wide", importance: "high", role: "Commissioner for Industrial Strategy (DG GROW)", relevance: "Controls simplification agenda and competitiveness balance. Shapes how sustainability regulation impacts industry." },
    { stkId: "STK-003", name: "DG ENV", organization: "European Commission", category: "EU Institution", geography: "EU-wide", importance: "high", role: "Directorate-General for Environment", relevance: "Leads PPWR implementation, PFAS restriction, circular economy policy. Primary regulatory body for packaging." },
    { stkId: "STK-004", name: "DG GROW", organization: "European Commission", category: "EU Institution", geography: "EU-wide", importance: "high", role: "Directorate-General for Internal Market, Industry", relevance: "Leads ESPR/DPP, textile strategy, product sustainability. Shapes industrial compliance requirements." },
    { stkId: "STK-005", name: "DG TAXUD", organization: "European Commission", category: "EU Institution", geography: "EU-wide", importance: "medium", role: "Directorate-General for Taxation and Customs", relevance: "Manages CBAM, customs reform, de minimis duties. Affects supply chain costs and cross-border logistics." },
    { stkId: "STK-006", name: "ENVI Committee", organization: "European Parliament", category: "EU Institution", geography: "EU-wide", importance: "high", role: "Committee on Environment, Public Health and Food Safety", relevance: "Lead committee on PPWR, ESPR, circular economy. Shapes final regulation text through amendments." },
    { stkId: "STK-007", name: "CEN/CENELEC JTC 24", organization: "CEN/CENELEC", category: "Standards Body", geography: "EU-wide", importance: "high", role: "Joint Technical Committee on DPP Standards", relevance: "Developing technical standards (prEN 1821x) for Digital Product Passport. Standards define data carrier and content requirements." },
    { stkId: "STK-008", name: "ECHA", organization: "European Chemicals Agency", category: "Regulator", geography: "EU-wide", importance: "high", role: "EU chemicals regulator — PFAS restriction", relevance: "Leading PFAS universal restriction process. Outcome directly affects packaging coatings and materials." },
    { stkId: "STK-009", name: "EUROPEN", organization: "EUROPEN", category: "Trade Association", geography: "EU-wide", importance: "high", role: "European Organisation for Packaging and the Environment", relevance: "Primary packaging industry voice in EU policy. Shapes industry response to PPWR and circular economy regulation." },
    { stkId: "STK-010", name: "EURATEX", organization: "EURATEX", category: "Trade Association", geography: "EU-wide", importance: "medium", role: "European Apparel and Textile Confederation", relevance: "Represents textile/apparel industry interests. Shapes DPP and textile strategy implementation." },
    { stkId: "STK-011", name: "Ellen MacArthur Foundation", organization: "Ellen MacArthur Foundation", category: "NGO", geography: "Global", importance: "high", role: "Leading circular economy advocate", relevance: "Sets circular economy benchmarks. Their New Plastics Economy and Fashion commitments influence brand procurement." },
    { stkId: "STK-012", name: "Zero Waste Europe", organization: "Zero Waste Europe", category: "NGO", geography: "EU-wide", importance: "medium", role: "Anti-waste and reuse advocacy", relevance: "Pushes for aggressive PPWR reuse targets and packaging reduction. Influences regulatory ambition levels." },
    { stkId: "STK-013", name: "CITEO / Citeo Pro", organization: "CITEO", category: "EPR Scheme", geography: "France", importance: "high", role: "French EPR scheme operator", relevance: "Manages EPR for household and professional packaging in France. Sets eco-contribution rates and compliance requirements." },
    { stkId: "STK-014", name: "ZSVR", organization: "ZSVR", category: "EPR Scheme", geography: "Germany", importance: "high", role: "German packaging registry (LUCID)", relevance: "Operates Germany's packaging producer registry. Compliance required for German market access." },
    { stkId: "STK-015", name: "PackUK", organization: "PackUK", category: "EPR Scheme", geography: "UK", importance: "medium", role: "UK packaging EPR scheme", relevance: "UK modulated EPR fees from Oct 2026. Recyclability-based fee structure incentivizes sustainable packaging." },
    { stkId: "STK-016", name: "Avery Dennison", organization: "Avery Dennison", category: "Competitor", geography: "Global", importance: "high", role: "Market leader in RFID, digital identity, labels", relevance: "Primary competitor in digital identity and labeling. $8.9B revenue. atma.io DPP platform sets competitive benchmark." },
    { stkId: "STK-017", name: "SML Group", organization: "SML Group", category: "Competitor", geography: "Global", importance: "high", role: "Brand identification and RFID solutions", relevance: "Most direct competitor to Mainetti. $600M+ PE investment makes them well-capitalized for expansion." },
    { stkId: "STK-018", name: "LVMH", organization: "LVMH", category: "Customer", geography: "Global", importance: "high", role: "World's largest luxury group", relevance: "Major potential client for premium packaging. Zero-virgin-plastic commitment drives immediate material requirements." },
    { stkId: "STK-019", name: "Inditex", organization: "Inditex", category: "Customer", geography: "Global", importance: "high", role: "World's largest fashion retailer (Zara)", relevance: "Green to Pack circular hanger program sets industry standards. Major volume client for hangers and packaging." },
    { stkId: "STK-020", name: "H&M Group", organization: "H&M Group", category: "Customer", geography: "Global", importance: "high", role: "Global fashion retailer", relevance: "100% recycled/sustainable packaging by 2030. Major procurement influence." },
    { stkId: "STK-021", name: "Kering", organization: "Kering", category: "Customer", geography: "Global", importance: "high", role: "Luxury group (Gucci, Saint Laurent)", relevance: "Eliminate plastic packaging commitment. Premium sustainable packaging demand." },
    { stkId: "STK-022", name: "Zalando", organization: "Zalando", category: "Customer", geography: "EU-wide", importance: "medium", role: "Largest European online fashion platform", relevance: "Requiring DPP for brand listings. Setting DPP as market access requirement ahead of regulation." },
    { stkId: "STK-023", name: "Selfridges", organization: "Selfridges", category: "Customer", geography: "UK", importance: "medium", role: "Premium UK department store", relevance: "DPP required for new brand onboarding. Premium retail setting sustainability procurement standards." },
    { stkId: "STK-024", name: "Cyprus EU Presidency", organization: "Council of the EU", category: "EU Institution", geography: "EU-wide", importance: "medium", role: "H1 2026 Council Presidency", relevance: "Shapes Council agenda including PPWR implementation priorities and simplification agenda." },
    { stkId: "STK-025", name: "Changing Markets Foundation", organization: "Changing Markets Foundation", category: "NGO", geography: "EU-wide", importance: "medium", role: "Greenwashing and corporate accountability watchdog", relevance: "\"Spinning Greenwash\" Dec 2025 report on recycled polyester microplastics. Influences public debate on sustainability claims." },
  ];

  for (const s of stakeholdersData) {
    storage.createStakeholder(s);
  }

  // ==================== COMPETITORS ====================
  const competitorsData = [
    { compId: "COMP-001", name: "Avery Dennison", description: "Global materials science and digital identification leader. Core competitor in RFID, labels, and DPP infrastructure via atma.io platform.", threatLevel: "high", recentMoves: '["Launched Optica RFID portfolio at NRF 2025","Expanded luxury label materials (Infinity/Sensorial Collections)","Launched clean-separation recycling adhesives at Labelexpo 2025","Acquired Meridian flooring adhesives for $390M"]', overlapAreas: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', revenue: "$8.9B", employees: "35,000+", keyStrength: "End-to-end digital identity platform (atma.io) with broadest RFID portfolio and brand recognition." },
    { compId: "COMP-002", name: "SML Group", description: "Most direct competitor to Mainetti in brand identification, RFID, and packaging solutions. Recently received $600M+ PE investment.", threatLevel: "high", recentMoves: '["Received $600M+ PE from FountainVest and CPE (Nov 2025)","Won 2026 SEAL Award for InfuseRFID","Reduced Scope 1+2 emissions 12.9% in 2025"]', overlapAreas: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', revenue: "Not disclosed", employees: "5,000+", keyStrength: "InfuseRFID survives wet apparel processing — unique technical advantage. Now well-capitalised for aggressive expansion." },
    { compId: "COMP-003", name: "Checkpoint Systems", description: "Retail solutions provider specializing in RFID, loss prevention, and retail analytics. Part of CCL Industries.", threatLevel: "medium-high", recentMoves: '["C&A 1,300-store RFID rollout (inventory accuracy 70%→95%)","Launched integrated RFID checkout solution (Feb 2026)","Driving factory-level RFID as defining trend of 2026"]', overlapAreas: '["Retail Experience","Product Branding"]', revenue: "Part of CCL Industries ($6.6B)", employees: "3,000+", keyStrength: "Strongest retail-facing RFID deployment capability. C&A case study is compelling reference." },
    { compId: "COMP-004", name: "Smurfit Westrock", description: "World's largest integrated paper and packaging company. $31.2B combined revenue. Now using AI for luxury packaging design.", threatLevel: "medium", recentMoves: '["Using AI to design luxury packaging","Publishing retail trends reports targeting fashion brands","Merged Smurfit Kappa and WestRock (2024)"]', overlapAreas: '["Product Branding","Supply Chain / Product Movement"]', revenue: "$31.2B", employees: "100,000+", keyStrength: "Massive scale advantage in corrugated/paper packaging. AI-driven design targeting luxury market." },
    { compId: "COMP-005", name: "DS Smith / International Paper", description: "DS Smith acquired by International Paper (Jan 2025). Major European packaging player with 1.7B+ plastic pieces replaced with recyclable alternatives.", threatLevel: "medium", recentMoves: '["Acquired by International Paper for ~$10B","Planning EMEA spinout","1.7B+ plastic pieces replaced with recyclable alternatives"]', overlapAreas: '["Supply Chain / Product Movement"]', revenue: "$7.2B (DS Smith pre-acquisition)", employees: "30,000+", keyStrength: "Leader in plastic-to-paper substitution. Circular design capability at scale." },
    { compId: "COMP-006", name: "Sealed Air / CD&R", description: "Protective and transit packaging provider being acquired by CD&R for $10.3B. Cryovac and AUTOBAG brands.", threatLevel: "low-medium", recentMoves: '["Being acquired by CD&R for $10.3B (mid-2026 close)","Launched AUTOBAG 850HB hybrid poly/paper mailer","Cryovac MonoPro recycle-ready packaging"]', overlapAreas: '["Supply Chain / Product Movement"]', revenue: "$5.5B", employees: "17,000", keyStrength: "Market leader in protective packaging. Integration uncertainty may create client acquisition opportunities." },
    { compId: "COMP-007", name: "Braiform", description: "Hanger reuse specialist saving 300M hangers/year. Most direct competitor in circular hanger programs.", threatLevel: "medium", recentMoves: '["300M hangers/year saved via reuse programs","Expanding circular hanger services to more retail chains","Positioning as sustainability-first hanger provider"]', overlapAreas: '["Retail Experience"]', revenue: "Not disclosed", employees: "1,000+", keyStrength: "Reuse-first business model. Strong circular credentials that directly challenge Hangerloop positioning." },
    { compId: "COMP-008", name: "(re)x / Arch & Hook", description: "Premium sustainable hanger brands using ocean plastic and recycled materials. Targeting luxury and premium retail.", threatLevel: "low-medium", recentMoves: '["Ocean-plastic premium hangers gaining traction","Partnering with luxury brands on sustainable retail fixtures","FSC paper hanger alternatives"]', overlapAreas: '["Retail Experience"]', revenue: "Not disclosed", employees: "500+", keyStrength: "Premium sustainability positioning with ocean-plastic story. Appeals to luxury brand ESG messaging." },
  ];

  for (const c of competitorsData) {
    storage.createCompetitor(c);
  }

  // ==================== OPPORTUNITIES & RISKS ====================
  const orData = [
    { orId: "OPP-001", title: "DPP-ready label infrastructure — first-mover advantage", description: "Digital Product Passport creates mandatory demand for QR-code-enabled labels and tags on every garment. Mainetti can build end-to-end DPP label solutions before competitors.", type: "opportunity", priority: 1, suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "short-term", impactLevel: "critical" },
    { orId: "OPP-002", title: "Circular hanger programs as procurement differentiator", description: "Inditex, H&M, and others making circularity a procurement criterion. Hangerloop and Polyloop programs are verified proof points.", type: "opportunity", priority: 2, suites: '["Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "immediate", impactLevel: "high" },
    { orId: "OPP-003", title: "PPWR compliance advisory as a service", description: "Clients face complex PPWR compliance requirements. Mainetti can offer packaging compliance audits, label reviews, and EPR registration support as value-added services.", type: "opportunity", priority: 3, suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "immediate", impactLevel: "high" },
    { orId: "OPP-004", title: "Luxury plastic-free packaging demand surge", description: "LVMH, Kering, and premium brands eliminating plastic from packaging. Mainetti's bespoke boxes, fabric dust bags, and paper-based solutions directly address this demand.", type: "opportunity", priority: 4, suites: '["Product Branding"]', timeHorizon: "immediate", impactLevel: "high" },
    { orId: "OPP-005", title: "Cross-suite integration advantage over siloed competitors", description: "No competitor spans branding + retail + supply chain the way Mainetti does. The regulatory convergence (PPWR + DPP + EPR) rewards integrated suppliers.", type: "opportunity", priority: 5, suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]', timeHorizon: "short-term", impactLevel: "high" },
    { orId: "RISK-001", title: "SML Group aggressive expansion post-PE investment", description: "SML's $600M+ investment enables aggressive pricing, acquisitions, and capability expansion. Risk of losing competitive ground in RFID and digital identity.", type: "risk", priority: 1, suites: '["Product Branding","Retail Experience"]', timeHorizon: "immediate", impactLevel: "high" },
    { orId: "RISK-002", title: "PPWR compliance failure — market access risk", description: "Non-compliance with PPWR by August 2026 means packaging cannot be placed on EU market. Risk of client delivery disruption.", type: "risk", priority: 2, suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "immediate", impactLevel: "critical" },
    { orId: "RISK-003", title: "Paper hanger competitive convergence", description: "Multiple competitors launching paper/sustainable hanger alternatives. Mainetti's Paperform advantage may erode as market catches up.", type: "risk", priority: 3, suites: '["Retail Experience"]', timeHorizon: "short-term", impactLevel: "medium" },
    { orId: "RISK-004", title: "Avery Dennison DPP platform dominance", description: "Avery Dennison's atma.io platform may become the de facto DPP infrastructure standard. Risk of Mainetti labels being commoditized.", type: "risk", priority: 4, suites: '["Product Branding"]', timeHorizon: "short-term", impactLevel: "high" },
    { orId: "RISK-005", title: "Material cost inflation from regulatory mandates", description: "Recycled content mandates, PFAS restrictions, and CBAM may increase input material costs across all product suites.", type: "risk", priority: 5, suites: '["Product Branding","Supply Chain / Product Movement"]', timeHorizon: "medium-term", impactLevel: "medium" },
  ];

  for (const or of orData) {
    storage.createOpportunityRisk(or);
  }

  // ==================== MILESTONES ====================
  const milestonesData = [
    { msId: "MS-001", date: "2026-03-31", title: "CEN DPP Standards Publication Deadline", regulation: "DPP-Textile", description: "CEN/CENELEC JTC 24 standards (prEN 1821x) defining DPP technical requirements due for publication.", impactLevel: "high", suites: '["Product Branding","Supply Chain / Product Movement"]' },
    { msId: "MS-002", date: "2026-05-31", title: "First CBAM Certificate Purchases", regulation: "CBAM", description: "Importers must purchase first CBAM certificates based on 2025 emissions declarations.", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]' },
    { msId: "MS-003", date: "2026-07-01", title: "French B2B EPR Levies Launch", regulation: "FR-EPR-Pro", description: "Citeo Pro professional packaging EPR levies begin. All B2B packaging on French market must register.", impactLevel: "high", suites: '["Supply Chain / Product Movement"]' },
    { msId: "MS-004", date: "2026-07-01", title: "EU De Minimis Customs Duty Starts", regulation: "EU-Customs", description: "€3 minimum duty on all imported consignments including sub-€150 parcels.", impactLevel: "medium", suites: '["Supply Chain / Product Movement"]' },
    { msId: "MS-005", date: "2026-07-19", title: "ESPR Unsold Goods Destruction Ban", regulation: "ESPR", description: "Large and medium enterprises prohibited from destroying unsold textiles and footwear.", impactLevel: "critical", suites: '["Retail Experience","Supply Chain / Product Movement"]' },
    { msId: "MS-006", date: "2026-08-12", title: "PPWR Full Application Date", regulation: "PPWR", description: "EU Packaging and Packaging Waste Regulation applies across all 27 Member States. Compliance mandatory.", impactLevel: "critical", suites: '["Product Branding","Retail Experience","Supply Chain / Product Movement"]' },
    { msId: "MS-007", date: "2026-09-27", title: "ECGT Greenwashing Ban Active", regulation: "ECGT", description: "Generic environmental claims banned. All sustainability messaging must be substantiated and verified.", impactLevel: "critical", suites: '["Product Branding","Supply Chain / Product Movement"]' },
    { msId: "MS-008", date: "2026-10-01", title: "UK Modulated EPR Fees Enforced", regulation: "UK-EPR", description: "PackUK modulated EPR fees based on recyclability enter full enforcement.", impactLevel: "medium", suites: '["Supply Chain / Product Movement","Product Branding"]' },
    { msId: "MS-009", date: "2026-12-30", title: "EUDR Application — Large Operators", regulation: "EUDR", description: "EU Deforestation Regulation applies to large operators. Paper and leather supply chain due diligence required.", impactLevel: "medium", suites: '["Product Branding","Supply Chain / Product Movement"]' },
  ];

  for (const m of milestonesData) {
    storage.createMilestone(m);
  }

  // ==================== ADVISORY ITEMS ====================
  const advisoryData = [
    { itemId: "WC-001", category: "weekly-change", title: "ESPR Working Table meets in Milan — DPP operational transition for fashion", description: "Multi-stakeholder working group defining practical DPP implementation.", date: "Mar 23, 2026", source: "European Climate Pact", sortOrder: 1 },
    { itemId: "WC-002", category: "weekly-change", title: "CSRD Omnibus I enters force — scope narrowed to >1,000 employees AND >€450M", description: "Directive (EU) 2026/470 published, threshold significantly raised.", date: "Mar 19, 2026", source: "Gibson Dunn / White & Case", sortOrder: 2 },
    { itemId: "WC-003", category: "weekly-change", title: "SML InfuseRFID wins 2026 SEAL Sustainable Product Award", description: "Competitor gaining sustainability recognition.", date: "Mar 18, 2026", source: "Fibre2Fashion", sortOrder: 3 },
    { itemId: "WC-004", category: "weekly-change", title: "ECHA RAC finalizing PFAS restriction option — 60-day consultation to follow", description: "PFAS ban moving forward with packaging implications.", date: "Mar 15, 2026", source: "ECHA / Plastics Engineering", sortOrder: 4 },
    { itemId: "WC-005", category: "weekly-change", title: "CEN DPP standards (prEN 1821X) deadline March 31 — publication to follow", description: "Technical standards for Digital Product Passport finalizing.", date: "Mar 10, 2026", source: "CEN/CENELEC", sortOrder: 5 },
    { itemId: "TC-001", category: "tell-clients", title: "Your packaging labels need a compliance audit now", description: "PPWR requires Declarations of Conformity, traceability identifiers, and manufacturer details on all EU-market packaging from August 12. Greenwashing rules ban generic sustainability claims from September 27. Every hangtag and label needs review.", sortOrder: 1 },
    { itemId: "TC-002", category: "tell-clients", title: "DPP-ready labels are becoming a market access requirement", description: "Zalando and Selfridges already require valid Digital Product Passports before listing brands. The EU mandate follows in 2027-2028. QR-code-integrated labels are no longer optional — they're the cost of doing business.", sortOrder: 2 },
    { itemId: "TC-003", category: "tell-clients", title: "Circular packaging credentials are now a procurement criterion", description: "From closed-loop hangers (Inditex Green to Pack) to recycled-content mandates (PPWR 2030), brands that can prove circularity win shelf space. Mainetti's Hangerloop, Polyloop, and FSC credentials are verified proof points.", sortOrder: 3 },
    { itemId: "PF-001", category: "prepare-for", title: "QR codes become the universal packaging format", description: "By 2028, QR codes will be mandatory across EPR labels (2027), Digital Product Passports (~2028), PPWR harmonized labels (2028), and reusable packaging (2029). Build modular QR label infrastructure now.", horizon: "2027-2029", sortOrder: 1 },
    { itemId: "PF-002", category: "prepare-for", title: "PPWR recyclability grades reshape material choices", description: "From 2030, all packaging must be recyclable (Grade C or above) with 35% recycled plastic content minimum. Products not meeting these thresholds will be banned from EU market. Design for Recycling assessment is the new baseline.", horizon: "2028-2030", sortOrder: 2 },
    { itemId: "PF-003", category: "prepare-for", title: "Traceability convergence across CSDDD, DPP, and PPWR", description: "These three regulatory frameworks are creating a single demand for end-to-end supply chain data. Mainetti's position across branding, retail, and supply chain packaging makes it a natural integration point.", horizon: "2027-2029", sortOrder: 3 },
  ];

  for (const a of advisoryData) {
    storage.createAdvisoryItem(a);
  }

  // Set initial meta
  storage.setMeta("lastScanAt", new Date().toISOString());
  storage.setMeta("version", "1.0");

  console.log("[SEED] Database seeded successfully.");
}
